sudo: required
language: generic

service:
    - docker

before_install:
    - docker build -t bogdaan90/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true bogdaan90/docker-react npm run test

deploy:
    provider: elastibeanstalk
    region: "eu-west-2"
    app: "docker-react"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-eu-west-2-499973093935"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
